# Pre-cargar el fondo de pantalla en memoria (reemplaza la ruta por tu imagen favorita)
preload = ~/.config/hypr/wallpaper.png

# Establecer el fondo de pantalla en tu monitor
wallpaper = ,~/.config/hypr/wallpaper.png

# Desactivar los mensajes de splash flotantes sobre el fondo
splash = false